---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-loadgen
spec:
  template:
    metadata:
      name: mongo-loadgen
      labels:
        loadgen_lkey: loadgen_lvalue
    spec:
      restartPolicy: Never
      containers:
      - name: mongo-loadgen
        image: openebs/tests-mongo-client
        command: ["/bin/bash"]
        args: ["-c", "./sysbench/sysbench --mongo-write-concern=1 --mongo-url='mongodb://podname.servicename' --mongo-database-name=database_name --test=./sysbench/tests/mongodb/oltp.lua --oltp_table_size=100 --oltp_tables_count=10 --num-threads=10 --rand-type=pareto --report-interval=10 --max-requests=0 --max-time=600 --oltp-point-selects=10 --oltp-simple-ranges=1 --oltp-sum-ranges=1 --oltp-order-ranges=1 --oltp-distinct-ranges=1 --oltp-index-updates=1 --oltp-non-index-updates=1 --oltp-inserts=1 run"]
        tty: true

